---

- name: Initial server
  hosts: localhost
  become: true
  tasks:

    - name: Update Index
      apt:
        update_cache: yes

    - name: Install Packages
      apt:
        pkg: 
        - python3
        - htop
        - tmux
        - ninja-build
        - gettext 
        - cmake
        - unzip 
        - curl 
        - build-essential

    - name: Git checkout stable neovim
      git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: /srv/checkout
        clone: yes
        version: stable

    - name: Build Neovim
      shell: 
        cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo
        chdir: /srv/checkout/

    - name: Install Neovim
      shell: 
        cmd: sudo make install
        chdir: /srv/checkout/

